import { post, postJson, postParamsConcatFun, get, postRequestExcelFun } from '../apiFun';

export const getDeviceList = params => postJson('getDeviceList', params);
export const getDeviceSelectors = params => postJson('getDeviceSelectors', params);
export const getDmpList = params => post('getDmpList', params);
export const getDmpUserList = params => post('getDmpUserList', params);
export const getDetails = params => postJson('getDetails', params);
export const addDevice = params => postJson('addDevice', params);
export const submitDeviceInfo = params => postJson('submitDeviceInfo', params);
// export const getPosition = params => post('getPosition', params);
// export const getLog = params => postJson('getLog', params);
export const getAddGronp = params => post('getAddGronp', params);
export const submitGronp = params => post('submitGronp', params);
export const getAddUser = params => post('getAddUser', params);
export const getModifyUser = params => post('getModifyUser', params);
export const submitUser = params => post('submitUser', params);
export const getDmpMakerAll = params => post('getDmpMakerAll', params);
export const getSubscribeList = params => get('getSubscribeList', params);
export const getDeviceTypeAndMakerAndModel = params => post('getDeviceTypeAndMakerAndModel', params);
export const getDmpAllUser = params => post('getDmpAllUser', params);
export const addSubscribe = params => postJson('addSubscribe', params);
export const delSubscribe = params => post('delSubscribe', params);
export const getSubscribeInfo = params => post('getSubscribeInfo', params);
export const modifySubscribe = params => post('modifySubscribe', params);
export const batchExport = params => postRequestExcelFun('batchExport', params);
export const downloadTemplate = params => postRequestExcelFun('downloadTemplate', params);
export const uploadPreview = params => post('uploadPreview', params);
export const uploadFile = params => postJson('uploadFile', params);
export const getProvinceList = params => postJson('getProvinceList', params);
export const getCityList = params => postParamsConcatFun('getCityList', params);
export const getCountryList = params => postParamsConcatFun('getCountryList', params);
